/*
 * This file is automatically generated. Do not edit this file directly. Modify the
 * index.components section of index.yaml instead
 * Run "ant angular.generate-index-files" in the build directory to update the generated
 * file.
 */

import { Type } from "@angular/core";
import { AdhocClientService } from '../common/services/AdhocClientService';

export const MODULE_SERVICES: Type<any>[] = [
  AdhocClientService
];
