/*
 * This file is automatically generated. Do not edit this file directly. Modify the
 * index.components section of index.yaml instead
 * Run "ant angular.generate-index-files" in the build directory to update the generated
 * file.
 */

import { Type } from "@angular/core";
import { PortalTitleBarComponent } from "./titlebar/portal-title-bar.component";
import { PortalReportComponent } from "./report/portal-report.component";
import { WelcomePageComponent } from "./welcome/welcome-page.component";

export const MODULE_COMPONENTS: Type<any>[] = [
  PortalTitleBarComponent,
  PortalReportComponent,
  WelcomePageComponent
];
